/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.cecar.vistas;

import edu.cecar.controladores.ControladorCliente;
import edu.cecar.modelos.Perfil;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

/**
 *
 * @author Vincenzo Angelone
 */
public final class VistaLogPanel extends javax.swing.JFrame {

    /**
     * Creates new form VistaLogPanel
     */
    static boolean conectado;

    static ControladorCliente controladorCliente = new ControladorCliente();

    public VistaLogPanel() {
        initComponents();
        this.setLocationRelativeTo(null);
        panel_registro.setVisible(false);
        String path = System.getProperty("user.dir");
        Image icon = Toolkit.getDefaultToolkit().getImage(path + "src\\main\\resources\\Captura1.png");
        this.setIconImage(icon);
        if (conectado == false) {
            if (controladorCliente.conectarClienteServidor("127.0.0.1", 17000) == false) {
                JOptionPane.showMessageDialog(null, "No hay conexion con el servidor, intente nuevamente.");
                System.exit(0);
            }
            conectado = true;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        panel_entrar = new javax.swing.JPanel();
        bt_Entrar = new javax.swing.JButton();
        pass_password = new javax.swing.JPasswordField();
        text_Usuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bt_registrarse = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        panel_registro = new javax.swing.JPanel();
        bt_registro = new javax.swing.JButton();
        pass_passwordRegistro = new javax.swing.JPasswordField();
        txt_idUsuarioRegistro = new javax.swing.JTextField();
        labe_cedula = new javax.swing.JLabel();
        label_password = new javax.swing.JLabel();
        bt_Logearse = new javax.swing.JButton();
        label_nombres = new javax.swing.JLabel();
        label_apellidos = new javax.swing.JLabel();
        label_fechaNacimiento = new javax.swing.JLabel();
        label_departamento = new javax.swing.JLabel();
        label_celular = new javax.swing.JLabel();
        label_sexo = new javax.swing.JLabel();
        label_descripcion = new javax.swing.JLabel();
        txt_nombes = new javax.swing.JTextField();
        txt_apellidos = new javax.swing.JTextField();
        box_sexo = new javax.swing.JComboBox<>();
        txt_celular = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        area_descripcion = new javax.swing.JTextArea();
        box_departamento = new javax.swing.JComboBox<>();
        fecha_nacimiento = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RESOC");
        setBackground(new java.awt.Color(204, 204, 204));
        setMinimumSize(new java.awt.Dimension(679, 635));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 102, 0));
        jPanel1.setForeground(new java.awt.Color(204, 102, 0));
        jPanel1.setMinimumSize(new java.awt.Dimension(687, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 687, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 680, 30);

        jPanel2.setBackground(new java.awt.Color(51, 153, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(687, 60));
        jPanel2.setLayout(null);

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(240, 240, 240));
        jLabel13.setText("RED SOCIAL CECAR");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(170, 10, 370, 40);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 30, 680, 60);

        panel_entrar.setBackground(new java.awt.Color(255, 255, 255));
        panel_entrar.setPreferredSize(new java.awt.Dimension(687, 484));

        bt_Entrar.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        bt_Entrar.setText("Iniciar Sesión");
        bt_Entrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_Entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_EntrarActionPerformed(evt);
            }
        });

        pass_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pass_passwordKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pass_passwordKeyTyped(evt);
            }
        });

        text_Usuario.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        text_Usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                text_UsuarioKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                text_UsuarioKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel3.setText("Usuario:");

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel2.setText("Contraseña: ");

        bt_registrarse.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        bt_registrarse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baseline_person_add_black_18dp.png"))); // NOI18N
        bt_registrarse.setText("Registro");
        bt_registrarse.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_registrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_registrarseActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Captura32.PNG"))); // NOI18N

        javax.swing.GroupLayout panel_entrarLayout = new javax.swing.GroupLayout(panel_entrar);
        panel_entrar.setLayout(panel_entrarLayout);
        panel_entrarLayout.setHorizontalGroup(
            panel_entrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_entrarLayout.createSequentialGroup()
                .addContainerGap(236, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(191, 191, 191))
            .addGroup(panel_entrarLayout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addGroup(panel_entrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_entrarLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pass_password, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_entrarLayout.createSequentialGroup()
                        .addComponent(bt_Entrar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_registrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_entrarLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_entrarLayout.setVerticalGroup(
            panel_entrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_entrarLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(panel_entrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_entrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pass_password, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(panel_entrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_registrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_Entrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(185, Short.MAX_VALUE))
        );

        getContentPane().add(panel_entrar);
        panel_entrar.setBounds(0, 90, 680, 550);

        panel_registro.setBackground(new java.awt.Color(255, 255, 255));
        panel_registro.setMinimumSize(new java.awt.Dimension(687, 484));
        panel_registro.setLayout(null);

        bt_registro.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        bt_registro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baseline_person_add_black_18dp.png"))); // NOI18N
        bt_registro.setText("Registrarse");
        bt_registro.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_registroActionPerformed(evt);
            }
        });
        panel_registro.add(bt_registro);
        bt_registro.setBounds(480, 260, 120, 40);

        pass_passwordRegistro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pass_passwordRegistroKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pass_passwordRegistroKeyTyped(evt);
            }
        });
        panel_registro.add(pass_passwordRegistro);
        pass_passwordRegistro.setBounds(240, 70, 220, 30);

        txt_idUsuarioRegistro.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        txt_idUsuarioRegistro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_idUsuarioRegistroKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_idUsuarioRegistroKeyTyped(evt);
            }
        });
        panel_registro.add(txt_idUsuarioRegistro);
        txt_idUsuarioRegistro.setBounds(241, 26, 220, 30);

        labe_cedula.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        labe_cedula.setText("Cédula*:");
        panel_registro.add(labe_cedula);
        labe_cedula.setBounds(167, 26, 70, 30);

        label_password.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        label_password.setText("Contraseña*: ");
        panel_registro.add(label_password);
        label_password.setBounds(160, 70, 70, 30);

        bt_Logearse.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        bt_Logearse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baseline_home_black_18dp.png"))); // NOI18N
        bt_Logearse.setText("Inicio");
        bt_Logearse.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_Logearse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_LogearseActionPerformed(evt);
            }
        });
        panel_registro.add(bt_Logearse);
        bt_Logearse.setBounds(480, 190, 120, 40);

        label_nombres.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        label_nombres.setText("Nombres*:");
        panel_registro.add(label_nombres);
        label_nombres.setBounds(160, 110, 70, 30);

        label_apellidos.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        label_apellidos.setText("Apellidos*:");
        panel_registro.add(label_apellidos);
        label_apellidos.setBounds(160, 150, 70, 30);

        label_fechaNacimiento.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        label_fechaNacimiento.setText("Fecha de Nacimiento*:");
        panel_registro.add(label_fechaNacimiento);
        label_fechaNacimiento.setBounds(120, 230, 123, 30);

        label_departamento.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        label_departamento.setText("Departamento*:");
        panel_registro.add(label_departamento);
        label_departamento.setBounds(140, 270, 120, 30);

        label_celular.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        label_celular.setText("Número Celular:");
        panel_registro.add(label_celular);
        label_celular.setBounds(140, 310, 120, 30);

        label_sexo.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        label_sexo.setText("Sexo*:");
        panel_registro.add(label_sexo);
        label_sexo.setBounds(170, 190, 70, 30);

        label_descripcion.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        label_descripcion.setText("Descripción:");
        panel_registro.add(label_descripcion);
        label_descripcion.setBounds(140, 400, 78, 30);

        txt_nombes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombesActionPerformed(evt);
            }
        });
        txt_nombes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_nombesKeyPressed(evt);
            }
        });
        panel_registro.add(txt_nombes);
        txt_nombes.setBounds(240, 110, 220, 30);

        txt_apellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_apellidosActionPerformed(evt);
            }
        });
        txt_apellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_apellidosKeyPressed(evt);
            }
        });
        panel_registro.add(txt_apellidos);
        txt_apellidos.setBounds(240, 150, 220, 30);

        box_sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino", "Otro" }));
        panel_registro.add(box_sexo);
        box_sexo.setBounds(240, 190, 220, 25);

        txt_celular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_celularKeyPressed(evt);
            }
        });
        panel_registro.add(txt_celular);
        txt_celular.setBounds(240, 310, 220, 30);

        area_descripcion.setColumns(20);
        area_descripcion.setRows(5);
        jScrollPane1.setViewportView(area_descripcion);

        panel_registro.add(jScrollPane1);
        jScrollPane1.setBounds(240, 350, 220, 130);

        box_departamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sistemas", "Proyeccion Social", "Logística\t", "Financiera", "Compras", "Contabilidad", "Talento Humano", "Planificación Y Desarrollo" }));
        panel_registro.add(box_departamento);
        box_departamento.setBounds(240, 270, 220, 30);
        panel_registro.add(fecha_nacimiento);
        fecha_nacimiento.setBounds(240, 230, 220, 30);

        getContentPane().add(panel_registro);
        panel_registro.setBounds(0, 90, 680, 550);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_EntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_EntrarActionPerformed
        try {
            Perfil perfil = new Perfil();
            perfil.setIdusario(Integer.parseInt(text_Usuario.getText()));
            perfil.setPassword(pass_password.getText());
            if (controladorCliente.PeticionClientePerfil("login", perfil) == true && text_Usuario.getText().equals("") == false && pass_password.getText().equals("") == false) {
                dispose();
                java.awt.EventQueue.invokeLater(new Runnable() {
                    public void run() {
                        new VistaPrincipal(Integer.parseInt(text_Usuario.getText())).setVisible(true);
                    }
                });
            } else {
                JOptionPane.showMessageDialog(null, "Credenciales incorrectas.");
            }
        } catch (Exception ex) {

            JOptionPane.showMessageDialog(null, "No hay conexion con la base de datos, intente nuevamente.");
        }
    }//GEN-LAST:event_bt_EntrarActionPerformed

    private void pass_passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pass_passwordKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                Perfil perfil = new Perfil();
                perfil.setIdusario(Integer.parseInt(text_Usuario.getText()));
                perfil.setPassword(pass_password.getText());
                if (controladorCliente.PeticionClientePerfil("login", perfil) == true) {
                    dispose();
                    java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                            new VistaPrincipal(Integer.parseInt(text_Usuario.getText())).setVisible(true);
                        }
                    });
                } else {
                    JOptionPane.showMessageDialog(null, "Credenciales incorrectas.");
                }
            } catch (Exception ex) {

                JOptionPane.showMessageDialog(null, "No hay conexion con la base de datos, intente nuevamente.");
            }
        }

    }//GEN-LAST:event_pass_passwordKeyPressed

    private void bt_registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_registroActionPerformed
        // TODO add your handling code here:
        if (txt_idUsuarioRegistro.getText().equals("") == false && txt_nombes.getText().equals("") == false && txt_apellidos.getText().equals("") == false && pass_passwordRegistro.getText().equals("") == false) {
            try {
                Perfil perfil = new Perfil();
                perfil.setIdusario(Integer.parseInt(txt_idUsuarioRegistro.getText()));
                perfil.setPassword(pass_passwordRegistro.getText());
                perfil.setNombres(txt_nombes.getText());
                perfil.setApellidos(txt_apellidos.getText());
                perfil.setSexo(box_sexo.getSelectedItem().toString());
                java.sql.Date fechasql = new java.sql.Date(fecha_nacimiento.getDate().getTime());
                perfil.setFechanacimiento(fechasql);
                perfil.setDepartamento(box_departamento.getSelectedItem().toString());
                if (txt_celular.getText().equals("") == false) {
                    perfil.setCelular(Long.parseLong(txt_celular.getText()));
                }
                if (area_descripcion.getText().equals("") == false) {
                    perfil.setDescripcion(area_descripcion.getText());
                } else {
                    perfil.setDescripcion(null);
                }
                
                perfil.setFotoPerfil(null);
                if (controladorCliente.PeticionClientePerfil("registro", perfil) == true) {
                    JOptionPane.showMessageDialog(null, "Registro Completado!");
                    text_Usuario.setText("");
                    txt_idUsuarioRegistro.setText("");
                    pass_password.setText("");
                    pass_passwordRegistro.setText("");
                    txt_nombes.setText("");
                    txt_apellidos.setText("");
                    txt_celular.setText("");
                    pass_password.setText("");
                    area_descripcion.setText("");
                    box_departamento.setSelectedIndex(0);
                    box_sexo.setSelectedIndex(0);
                    panel_entrar.setVisible(true);
                    panel_registro.setVisible(false);
                } else {
                    JOptionPane.showMessageDialog(null, "Error datos erroneos o faltantes.");
                }

            } catch (Exception ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(null, "No hay conexion con la base de datos, intente nuevamente.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Algunos campos obligatorios están vacios");
        }
    }//GEN-LAST:event_bt_registroActionPerformed

    private void pass_passwordRegistroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pass_passwordRegistroKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txt_idUsuarioRegistro.getText().equals("") == true || txt_nombes.getText().equals("") == true || txt_apellidos.getText().equals("") == true || pass_passwordRegistro.getText().equals("") == true) {
                try {
                    Perfil perfil = new Perfil();
                    perfil.setIdusario(Integer.parseInt(txt_idUsuarioRegistro.getText()));
                    perfil.setPassword(pass_passwordRegistro.getText());
                    perfil.setNombres(txt_nombes.getText());
                    perfil.setApellidos(txt_apellidos.getText());
                    perfil.setSexo(box_sexo.getSelectedItem().toString());
                    java.sql.Date fechasql = new java.sql.Date(fecha_nacimiento.getDate().getTime());
                    perfil.setFechanacimiento(fechasql);
                    perfil.setDepartamento(box_departamento.getSelectedItem().toString());
                    if (txt_celular.getText().equals("") == false) {
                        perfil.setCelular(Long.parseLong(txt_celular.getText()));
                    }
                    if (area_descripcion.getText().equals("") == false) {
                        perfil.setDescripcion(area_descripcion.getText());
                    } else {
                        perfil.setDescripcion(null);
                    }
                    if (controladorCliente.PeticionClientePerfil("registro", perfil) == true) {
                        JOptionPane.showMessageDialog(null, "Registro Completado!");
                        text_Usuario.setText("");
                        txt_idUsuarioRegistro.setText("");
                        pass_password.setText("");
                        pass_passwordRegistro.setText("");
                        txt_nombes.setText("");
                        txt_apellidos.setText("");
                        txt_celular.setText("");
                        pass_password.setText("");
                        area_descripcion.setText("");
                        box_departamento.setSelectedIndex(0);
                        box_sexo.setSelectedIndex(0);
                        panel_entrar.setVisible(true);
                        panel_registro.setVisible(false);
                    } else {
                        JOptionPane.showMessageDialog(null, "Error datos erroneos o faltantes.");
                    }

                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "No hay conexion con la base de datos, intente nuevamente.");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Algunos campos obligatorios están vacios");
            }
        }
    }//GEN-LAST:event_pass_passwordRegistroKeyPressed

    private void bt_registrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_registrarseActionPerformed
        // TODO add your handling code here:
        text_Usuario.setText("");
        txt_idUsuarioRegistro.setText("");
        pass_password.setText("");
        pass_passwordRegistro.setText("");
        txt_nombes.setText("");
        txt_apellidos.setText("");
        txt_celular.setText("");
        pass_password.setText("");
        area_descripcion.setText("");
        box_departamento.setSelectedIndex(0);
        box_sexo.setSelectedIndex(0);
        panel_entrar.setVisible(false);
        panel_registro.setVisible(true);
    }//GEN-LAST:event_bt_registrarseActionPerformed

    private void bt_LogearseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_LogearseActionPerformed
        // TODO add your handling code here:
        text_Usuario.setText("");
        txt_idUsuarioRegistro.setText("");
        pass_password.setText("");
        pass_passwordRegistro.setText("");
        txt_nombes.setText("");
        txt_apellidos.setText("");
        txt_celular.setText("");
        pass_password.setText("");
        area_descripcion.setText("");
        box_departamento.setSelectedIndex(0);
        box_sexo.setSelectedIndex(0);
        panel_entrar.setVisible(true);
        panel_registro.setVisible(false);
    }//GEN-LAST:event_bt_LogearseActionPerformed

    private void text_UsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_UsuarioKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txt_idUsuarioRegistro.getText().equals("") == true || txt_nombes.getText().equals("") == true || txt_apellidos.getText().equals("") == true || pass_passwordRegistro.getText().equals("") == true) {
                try {
                    Perfil perfil = new Perfil();
                    perfil.setIdusario(Integer.parseInt(txt_idUsuarioRegistro.getText()));
                    perfil.setPassword(pass_passwordRegistro.getText());
                    perfil.setNombres(txt_nombes.getText());
                    perfil.setApellidos(txt_apellidos.getText());
                    perfil.setSexo(box_sexo.getSelectedItem().toString());
                    java.sql.Date fechasql = new java.sql.Date(fecha_nacimiento.getDate().getTime());
                    perfil.setFechanacimiento(fechasql);
                    perfil.setDepartamento(box_departamento.getSelectedItem().toString());
                    if (txt_celular.getText().equals("") == false) {
                        perfil.setCelular(Long.parseLong(txt_celular.getText()));
                    }
                    if (area_descripcion.getText().equals("") == false) {
                        perfil.setDescripcion(area_descripcion.getText());
                    } else {
                        perfil.setDescripcion(null);
                    }
                    if (controladorCliente.PeticionClientePerfil("registro", perfil) == true) {
                        JOptionPane.showMessageDialog(null, "Registro Completado!");
                        text_Usuario.setText("");
                        txt_idUsuarioRegistro.setText("");
                        pass_password.setText("");
                        pass_passwordRegistro.setText("");
                        txt_nombes.setText("");
                        txt_apellidos.setText("");
                        txt_celular.setText("");
                        pass_password.setText("");
                        area_descripcion.setText("");
                        box_departamento.setSelectedIndex(0);
                        box_sexo.setSelectedIndex(0);
                        panel_entrar.setVisible(true);
                        panel_registro.setVisible(false);
                    } else {
                        JOptionPane.showMessageDialog(null, "Error datos erroneos o faltantes.");
                    }

                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "No hay conexion con la base de datos, intente nuevamente.");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Algunos campos obligatorios están vacios");
            }
        }
    }//GEN-LAST:event_text_UsuarioKeyPressed

    private void txt_idUsuarioRegistroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_idUsuarioRegistroKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_txt_idUsuarioRegistroKeyPressed

    private void text_UsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_UsuarioKeyTyped
        // TODO add your handling code here
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_text_UsuarioKeyTyped

    private void pass_passwordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pass_passwordKeyTyped
        // TODO add your handling code here:
        if (!Character.isLetter(evt.getKeyChar()) && !Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_pass_passwordKeyTyped

    private void txt_idUsuarioRegistroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_idUsuarioRegistroKeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_idUsuarioRegistroKeyTyped

    private void pass_passwordRegistroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pass_passwordRegistroKeyTyped
        // TODO add your handling code here:
        if (!Character.isLetter(evt.getKeyChar()) && !Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_pass_passwordRegistroKeyTyped

    private void txt_nombesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombesActionPerformed

    private void txt_apellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_apellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_apellidosActionPerformed

    private void txt_nombesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombesKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txt_idUsuarioRegistro.getText().equals("") == true || txt_nombes.getText().equals("") == true || txt_apellidos.getText().equals("") == true || pass_passwordRegistro.getText().equals("") == true) {
                try {
                    Perfil perfil = new Perfil();
                    perfil.setIdusario(Integer.parseInt(txt_idUsuarioRegistro.getText()));
                    perfil.setPassword(pass_passwordRegistro.getText());
                    perfil.setNombres(txt_nombes.getText());
                    perfil.setApellidos(txt_apellidos.getText());
                    perfil.setSexo(box_sexo.getSelectedItem().toString());
                    java.sql.Date fechasql = new java.sql.Date(fecha_nacimiento.getDate().getTime());
                    perfil.setFechanacimiento(fechasql);
                    perfil.setDepartamento(box_departamento.getSelectedItem().toString());
                    if (txt_celular.getText().equals("") == false) {
                        perfil.setCelular(Long.parseLong(txt_celular.getText()));
                    }
                    if (area_descripcion.getText().equals("") == false) {
                        perfil.setDescripcion(area_descripcion.getText());
                    } else {
                        perfil.setDescripcion(null);
                    }
                    if (controladorCliente.PeticionClientePerfil("registro", perfil) == true) {
                        JOptionPane.showMessageDialog(null, "Registro Completado!");
                        text_Usuario.setText("");
                        txt_idUsuarioRegistro.setText("");
                        pass_password.setText("");
                        pass_passwordRegistro.setText("");
                        txt_nombes.setText("");
                        txt_apellidos.setText("");
                        txt_celular.setText("");
                        pass_password.setText("");
                        area_descripcion.setText("");
                        box_departamento.setSelectedIndex(0);
                        box_sexo.setSelectedIndex(0);
                        panel_entrar.setVisible(true);
                        panel_registro.setVisible(false);
                    } else {
                        JOptionPane.showMessageDialog(null, "Error datos erroneos o faltantes.");
                    }

                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "No hay conexion con la base de datos, intente nuevamente.");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Algunos campos obligatorios están vacios");
            }
        }
    }//GEN-LAST:event_txt_nombesKeyPressed

    private void txt_apellidosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_apellidosKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txt_idUsuarioRegistro.getText().equals("") == true || txt_nombes.getText().equals("") == true || txt_apellidos.getText().equals("") == true || pass_passwordRegistro.getText().equals("") == true) {
                try {
                    Perfil perfil = new Perfil();
                    perfil.setIdusario(Integer.parseInt(txt_idUsuarioRegistro.getText()));
                    perfil.setPassword(pass_passwordRegistro.getText());
                    perfil.setNombres(txt_nombes.getText());
                    perfil.setApellidos(txt_apellidos.getText());
                    perfil.setSexo(box_sexo.getSelectedItem().toString());
                    java.sql.Date fechasql = new java.sql.Date(fecha_nacimiento.getDate().getTime());
                    perfil.setFechanacimiento(fechasql);
                    perfil.setDepartamento(box_departamento.getSelectedItem().toString());
                    if (txt_celular.getText().equals("") == false) {
                        perfil.setCelular(Long.parseLong(txt_celular.getText()));
                    }
                    if (area_descripcion.getText().equals("") == false) {
                        perfil.setDescripcion(area_descripcion.getText());
                    } else {
                        perfil.setDescripcion(null);
                    }
                    if (controladorCliente.PeticionClientePerfil("registro", perfil) == true) {
                        JOptionPane.showMessageDialog(null, "Registro Completado!");
                        text_Usuario.setText("");
                        txt_idUsuarioRegistro.setText("");
                        pass_password.setText("");
                        pass_passwordRegistro.setText("");
                        txt_nombes.setText("");
                        txt_apellidos.setText("");
                        txt_celular.setText("");
                        pass_password.setText("");
                        area_descripcion.setText("");
                        box_departamento.setSelectedIndex(0);
                        box_sexo.setSelectedIndex(0);
                        panel_entrar.setVisible(true);
                        panel_registro.setVisible(false);
                    } else {
                        JOptionPane.showMessageDialog(null, "Error datos erroneos o faltantes.");
                    }

                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "No hay conexion con la base de datos, intente nuevamente.");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Algunos campos obligatorios están vacios");
            }
        }
    }//GEN-LAST:event_txt_apellidosKeyPressed

    private void txt_celularKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_celularKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txt_idUsuarioRegistro.getText().equals("") == true || txt_nombes.getText().equals("") == true || txt_apellidos.getText().equals("") == true || pass_passwordRegistro.getText().equals("") == true) {
                try {
                    Perfil perfil = new Perfil();
                    perfil.setIdusario(Integer.parseInt(txt_idUsuarioRegistro.getText()));
                    perfil.setPassword(pass_passwordRegistro.getText());
                    perfil.setNombres(txt_nombes.getText());
                    perfil.setApellidos(txt_apellidos.getText());
                    perfil.setSexo(box_sexo.getSelectedItem().toString());
                    java.sql.Date fechasql = new java.sql.Date(fecha_nacimiento.getDate().getTime());
                    perfil.setFechanacimiento(fechasql);
                    perfil.setDepartamento(box_departamento.getSelectedItem().toString());
                    if (txt_celular.getText().equals("") == false) {
                        perfil.setCelular(Long.parseLong(txt_celular.getText()));
                    }
                    if (area_descripcion.getText().equals("") == false) {
                        perfil.setDescripcion(area_descripcion.getText());
                    } else {
                        perfil.setDescripcion(null);
                    }
                    if (controladorCliente.PeticionClientePerfil("registro", perfil) == true) {
                        JOptionPane.showMessageDialog(null, "Registro Completado!");
                        text_Usuario.setText("");
                        txt_idUsuarioRegistro.setText("");
                        pass_password.setText("");
                        pass_passwordRegistro.setText("");
                        txt_nombes.setText("");
                        txt_apellidos.setText("");
                        txt_celular.setText("");
                        pass_password.setText("");
                        area_descripcion.setText("");
                        box_departamento.setSelectedIndex(0);
                        box_sexo.setSelectedIndex(0);
                        panel_entrar.setVisible(true);
                        panel_registro.setVisible(false);
                    } else {
                        JOptionPane.showMessageDialog(null, "Error datos erroneos o faltantes.");
                    }

                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "No hay conexion con la base de datos, intente nuevamente.");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Algunos campos obligatorios están vacios");
            }
        }
    }//GEN-LAST:event_txt_celularKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaLogPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaLogPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaLogPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaLogPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaLogPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area_descripcion;
    private javax.swing.JComboBox<String> box_departamento;
    private javax.swing.JComboBox<String> box_sexo;
    private javax.swing.JButton bt_Entrar;
    private javax.swing.JButton bt_Logearse;
    private javax.swing.JButton bt_registrarse;
    private javax.swing.JButton bt_registro;
    private com.toedter.calendar.JDateChooser fecha_nacimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labe_cedula;
    private javax.swing.JLabel label_apellidos;
    private javax.swing.JLabel label_celular;
    private javax.swing.JLabel label_departamento;
    private javax.swing.JLabel label_descripcion;
    private javax.swing.JLabel label_fechaNacimiento;
    private javax.swing.JLabel label_nombres;
    private javax.swing.JLabel label_password;
    private javax.swing.JLabel label_sexo;
    private javax.swing.JPanel panel_entrar;
    private javax.swing.JPanel panel_registro;
    private javax.swing.JPasswordField pass_password;
    private javax.swing.JPasswordField pass_passwordRegistro;
    private javax.swing.JTextField text_Usuario;
    private javax.swing.JTextField txt_apellidos;
    private javax.swing.JTextField txt_celular;
    private javax.swing.JTextField txt_idUsuarioRegistro;
    private javax.swing.JTextField txt_nombes;
    // End of variables declaration//GEN-END:variables
}
